### ISSUE TITLE
Documentation of Email 2-factor verification or Features?

### ISSUE THREAD

**Issue by edwardchanjw** [Cosync/CosyncJWTSample#1]
Hi, Do Cosync support Email 2-Factor Verification instead of Google Two factor Authentication only?

Awesome business model, but I am guessing the pricing wars already started as new entrance enter like [Cotter](https://www.cotter.app/). Your business is more on pre-cloud model, and all of the Cloud related pricing actually not viable, if my SaaS charge users around $0.1-$2, if their usage gonna be heavy, all earning almost gone to the cloud. But your business would work on niche, hopefully to see you scale well and prospect.

Thanks.

**Comment by rckrueger** [comment]
Edward, 

So Cosync also supports phone 2-factor verification through Twilio's SMS service - but there is a charge for that from Twilio. Unlike Cotter - CosyncJWT is specifically designed to be a JWT authentication service for MongoDB Realm. We are shortly going to release a self hosted version of CosyncJWT - so that a developer can install it on their own servers. Our business model is more adjunct developer tools for MongoDB Realm and collaborative software, than authentication service per se.

**Comment by edwardchanjw** [comment]
Great, feel free to closed this ticket.
Probably public documentation how to hardened self-hosted so even some medium SaaS can consider your solution , even better probably sell it on AWS marketplace, DigitalOcean marketplace vice versa. When you need to tap into different market.

**Comment by rckrueger** [comment]
Edward thanks for the great advice. Please stay in touch.
